import {
  AlertCircle,
  AlertTriangle,
  Check,
  ChevronLeft,
  ChevronRight,
  Clock,
  Eye,
  EyeOff,
  Image,
  Info,
  Lock,
  Mail,
  Plus,
  Search,
  Settings,
  Trash,
  User,
  X,
  XCircle,
} from 'lucide-react-native';

export const ICONS = {
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  eye: Eye,
  eyeOff: EyeOff,
  image: Image,
  info: Info,
  lock: Lock,
  mail: Mail,
  plus: Plus,
  search: Search,
  settings: Settings,
  trash: Trash,
  user: User,
  x: X,
  xCircle: XCircle,
} as const;
