export const BG_ASPECT_RATIO = 2559 / 5532;

export const PAGE_BG_COLOR = '#FBFAF9';

export const BG_FADE_DURATION_MS = 380;
export const PRE_OVERLAY_DELAY_MS = 500;
export const OVERLAY_FADE_DURATION_MS = 380;
export const WHITE_OVERLAY_OPACITY = 0.5;
export const PRE_JUMP_DELAY_MS = 500;
export const EXIT_FADE_DURATION_MS = 380;

export const JUMP_START_DELAY_MS =
  BG_FADE_DURATION_MS + PRE_OVERLAY_DELAY_MS + OVERLAY_FADE_DURATION_MS + PRE_JUMP_DELAY_MS;

export const LETTER_COUNT = 6;
export const LETTER_GAP = 4;
export const LETTER_JUMP_HEIGHT = -16;

export const LETTER_BOUNCE_DURATION_MS = 600;
export const LETTER_STAGGER_MS = 130;
export const LETTER_PAUSE_AFTER_ALL_MS = 320;
export const LETTER_PER_LETTER_PAUSE_MS =
  LETTER_STAGGER_MS * (LETTER_COUNT - 1) + LETTER_PAUSE_AFTER_ALL_MS;
export const LETTER_CYCLE_MS = LETTER_BOUNCE_DURATION_MS + LETTER_PER_LETTER_PAUSE_MS;

export const LETTER_SCALE = 0.135;
export const LETTER_C_WIDTH = Math.round(197 * LETTER_SCALE);
export const LETTER_O_WIDTH = Math.round(229 * LETTER_SCALE);
export const LETTER_K_WIDTH = Math.round(192 * LETTER_SCALE);

export const LETTER_C_RATIO = 591 / 675;
export const LETTER_O_RATIO = 687 / 672;
export const LETTER_K_RATIO = 576 / 918;
